### ISSUE TITLE
LiveView Native Clients: Use cleaners or JEP 419 instead of finalize

### ISSUE THREAD

**Issue by KronicDeth** [liveview-native/liveview-native-core-jetpack#5]
The Java community is slowly moving away from `finalize` on objects as in [JEP 421](https://openjdk.org/jeps/421).  JEP 421 points at [JEP 419: Foreign Function & Memory API](https://openjdk.org/jeps/419), which is in JDK 19, which we may want to adopt.

**Comment by AZholtkevych** [comment]
Doesn't make sense since we are using UniFFI
